use utoipa::{
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
    Modify, OpenApi,
};

use crate::errors;
use crate::routes::{admin, auth, business, health, moderation, monetization, profile, recommendation, search, seo, taxonomy, user};

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .description(Some("Enter your JWT access token"))
                        .build(),
                ),
            );
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        health::liveness,
        health::readiness,
        auth::register,
        auth::login,
        auth::refresh,
        auth::logout,
        auth::logout_all,
        user::get_me,
        business::create,
        business::get_public,
        business::get_management,
        business::update_profile,
        business::submit,
        business::archive,
        business::get_members,
        business::add_business_member,
        business::remove_business_member,
        business::change_role,
        taxonomy::get_categories,
        taxonomy::get_category,
        taxonomy::get_services,
        taxonomy::get_service,
        taxonomy::get_business_categories,
        taxonomy::add_business_category,
        taxonomy::remove_business_category_endpoint,
        taxonomy::set_primary_category_endpoint,
        taxonomy::get_business_services,
        taxonomy::add_business_service_endpoint,
        taxonomy::remove_business_service_endpoint,
        profile::get_presentation,
        profile::set_business_hours,
        profile::set_business_attributes,
        profile::set_business_social_links,
        profile::delete_media_item,
        moderation::get_cases,
        moderation::get_case_detail,
        moderation::start_review_endpoint,
        moderation::approve_endpoint,
        moderation::reject_endpoint,
        moderation::escalate_endpoint,
        moderation::suspend_business_endpoint,
        moderation::restore_business_endpoint,
        moderation::claim_business_endpoint,
        moderation::report_business_endpoint,
        search::search_businesses,
        search::autocomplete_suggestions,
        recommendation::get_recommendations,
        recommendation::get_similar_businesses,
        monetization::get_plans,
        monetization::subscribe_business_endpoint,
        monetization::verify_payment_endpoint,
        monetization::create_campaign_endpoint,
        monetization::get_sponsored_ads,
        seo::get_business_seo_endpoint,
        seo::get_landing_page_endpoint,
        admin::get_dashboard_endpoint,
        admin::list_users_endpoint,
        admin::suspend_user_endpoint,
        admin::restore_user_endpoint,
        admin::revoke_sessions_endpoint,
        admin::submit_appeal_endpoint,
        admin::list_appeals_endpoint,
        admin::resolve_appeal_endpoint,
        admin::list_flags_endpoint,
        admin::set_flag_endpoint,
        admin::list_configs_endpoint,
        admin::set_config_endpoint,
        admin::get_audits_endpoint,
    ),
    components(
        schemas(
            health::LivenessResponse,
            health::ReadinessResponse,
            health::DependencyHealth,
            errors::ApiErrorResponse,
            errors::ErrorDetail,
            auth::RegisterRequest,
            auth::LoginRequest,
            auth::RefreshRequest,
            auth::AuthSuccessResponse,
            application::use_cases::get_me::UserProfileDto,
            application::use_cases::business::CreateBusinessCommand,
            application::use_cases::business::BusinessDto,
            application::use_cases::business::PublicBusinessProfileDto,
            application::use_cases::business::LocationDto,
            application::use_cases::business::ContactDto,
            application::use_cases::members::MemberDto,
            application::use_cases::members::AddMemberCommand,
            application::use_cases::members::ChangeRoleCommand,
            application::use_cases::taxonomy::CategoryDto,
            application::use_cases::taxonomy::ServiceDto,
            application::use_cases::taxonomy::BusinessCategoryDto,
            application::use_cases::taxonomy::BusinessServiceDto,
            application::use_cases::taxonomy::AssignCategoryCommand,
            application::use_cases::taxonomy::AssignServiceCommand,
            application::use_cases::profile::PublicPresentationDto,
            application::use_cases::profile::MediaDto,
            application::use_cases::profile::AttributeItemDto,
            application::use_cases::profile::SocialLinkDto,
            application::use_cases::profile::SaveAttributesCommand,
            application::use_cases::profile::AttributePayload,
            application::use_cases::profile::SaveSocialLinksCommand,
            application::use_cases::profile::SocialLinkPayload,
            application::use_cases::moderation::ModerationCaseDto,
            application::use_cases::moderation::DecisionCommand,
            application::use_cases::moderation::SubmitClaimCommand,
            application::use_cases::moderation::CreateReportCommand,
            application::ports::search::SearchResultItemDto,
            application::ports::search::SearchResponseDto,
            application::ports::search::SuggestionItemDto,
            application::ports::search::SuggestionType,
            application::ports::recommendation::RecommendationItemDto,
            application::ports::recommendation::RecommendationResponseDto,
            application::ports::monetization::PlanDto,
            application::ports::monetization::PaymentDto,
            application::ports::monetization::SponsoredAdDto,
            application::ports::seo::BusinessSeoPageDto,
            application::ports::seo::CategoryLocationLandingDto,
            application::ports::admin::AdminUserDto,
            application::ports::admin::BusinessAppealDto,
            application::ports::admin::AuditLogEntryDto,
            application::use_cases::monetization::SubscribeCommand,
            application::use_cases::monetization::CreateCampaignCommand,
            application::use_cases::admin::SubmitAppealCommand,
            application::use_cases::admin::ResolveAppealCommand,
            application::use_cases::admin::UpdateFeatureFlagCommand,
            application::use_cases::admin::UpdateConfigCommand,
            domain::admin::AdminDashboardMetrics,
            domain::admin::AppealStatus,
            domain::admin::FeatureFlagItem,
            domain::admin::SystemConfigItem,
            domain::seo::PageMetadata,
            domain::seo::StructuredDataJsonLd,
            domain::seo::StructuredAddress,
            domain::seo::StructuredGeo,
            domain::monetization::Money,
            domain::monetization::Currency,
            business::UpdateProfileRequest,
            domain::membership::MembershipRole,
            domain::profile::BusinessHoursInterval,
            domain::profile::MediaType,
            domain::profile::SocialPlatform,
            domain::moderation::ClaimMethod,
            domain::moderation::ReportReason,
            domain::moderation::ModerationReasonCode,
            domain::recommendation::RecommendationSurface,
            domain::recommendation::CandidateSource,
        )
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "Health", description = "Health and readiness probes"),
        (name = "Auth", description = "Authentication and session management"),
        (name = "User", description = "User profile operations"),
        (name = "Business", description = "Business aggregate & membership operations"),
        (name = "Taxonomy", description = "Category & Service taxonomy management"),
        (name = "Profile", description = "Structured profile, media, hours, and attributes"),
        (name = "Moderation", description = "Admin moderation cases, claims & trust verification"),
        (name = "Search", description = "Full text search, geo-discovery & autocomplete"),
        (name = "Recommendation", description = "Personalized & contextual discovery"),
        (name = "Monetization", description = "Subscription plans, payments, ledger & sponsored ads"),
        (name = "SEO", description = "Metadata, Canonical URLs, Sitemaps & Landing Pages"),
        (name = "Admin", description = "Admin operations, RBAC, feature flags & platform control plane"),
    ),
    info(
        title = "Business Discovery Platform API",
        version = "1.0.0",
        description = "Complete Modular Monolith Backend with Admin Operations, Granular RBAC, Audit Trail & Security Controls"
    )
)]
pub struct ApiDoc;